baseURL = 'https://kakavand.me'
languageCode = 'fa-IR'
defaultContentLanguage = "fa"
title = 'امین کاکاوند'
theme = "typo-1.13.0"
buildFuture = true

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "بهترین وبلاگ امین کاکاوند در سطح اینترنت"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = ''
homeIntroContent = """
به بهترین **وبلاگ امین کاکاوند** در اینترنت خوش اومدید!

من امین کاکاوند هستم و در این وبلاگ در مورد استراتژی، کسب و کار، تکنولوژی، محصول و چیزهای دیگه می‌نویسم.
"""

# Collection to display on home
homeCollectionTitle = 'نوشته‌ها'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = false

# Social icons

[[params.social]]
name = "Youtube"
url = "https://www.youtube.com/@Amin.Kakavand"

[[params.social]]
name = "X"
url = "https://x.com/aminkakavand/"

[[params.social]]
name = "Instagram"
url = "https://www.instagram.com/kakavand.me/"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/aminkakavand/"

[[params.social]]
name = "rss"
url = "/index.xml"

# Main menu pages
[[params.menu]]
name = "خانه"
url = "/"

[[params.menu]]
name = "درباره من"
url = "/about"

[[params.menu]]
name = "۷ قدرت"
url = "/7powers"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Add settings for heading anchors
[markup.headings]
  autoHeadingID = true
  autoHeadingIDType = "github"

# Configure Table of Contents
[markup.tableOfContents]
  startLevel = 2 # Start TOC from H2
  endLevel = 3   # Include up to H3 (adjust if needed)
  ordered = false

# Giscus comments
# ‍[params.giscus]
# enable = true
# repo = "Amika93/kakavand.me"
# repoid = "R_kgDOONgtvg"
# category = "General"
# categoryid = "DIC_kwDOONgtvs4CoY6N"
# mapping = "pathname"
# data-strict="0"
# data-reactions-enabled="1"
# data-emit-metadata="1"
# data-input-position="top"
# data-theme="Fro"
# data-lang="fa"
# crossorigin="anonymous"

# [assets]
#   [[assets.js]]
#     src = "themes/typo-1.13.0/assets/js/obsidian-links.js"
#     target = "js/obsidian-links.js"
